title:        flexCarousel.js
description:  A simple, lightweight Flexbox carousel JavaScript plugin.
url:          https://flexcarousel.com
download:     https://github.com/tomhrtly/flexCarousel.js/releases/download/v0.2.1/flexCarousel-0.2.1.zip
version:      0.2.1

env:          development

markdown:     kramdown
permalink:    pretty

github:       https://github.com/tomhrtly/flexCarousel.js
twitter:      https://twitter.com/tomhrtly
mail:         tom@tomhrtly.com

plugins:
  - jekyll-redirect-from